### PR TITLE
Updated to .Net5.0 & Added session cookie

### PR DESCRIPTION
**Pull request by FaustVX**
Hi,

I really like your library, and I tried to execute it and it didn't compile because the runtime is now `net5.0`.

I also added a new launch configuration (I've renamed your Run config and added an Update config)

And I added the cookie SESSION in the launch configuration.

### CODE REVIEW

**Comment by encse** [comment]
you know what... i dont like it, because i dont want ppl to commit their session cookie.

**Comment by encse** [comment]
sorry

**Comment by encse** [comment]
i kept the .net 5 part, but I already fixed that on master.

**Comment by FaustVX** [comment]
Ok, No problem.
It's a good reason to not want it.

**Pull request merged**
